<?php

namespace App\Filament\Resources\Payrolls\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class PayrollForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('employee_id')
                    ->required()
                    ->disabled(true)
                    ->visible(false)
                    ->numeric(),
                TextInput::make('payroll_period_id')
                    ->required()
                    ->disabled(true)
                    ->visible(false)
                    ->numeric(),
                TextInput::make('employment_status')
                ->disabled(true)
                ->visible(false),
                TextInput::make('position')
                ->disabled(true)
                ->visible(false),
                TextInput::make('days_present')
                    ->required()
                    ->visible(false)
                    ->numeric()
                    ->disabled(true)
                    ->default(0),
                TextInput::make('days_absent')
                    ->required()
                    ->visible(false)
                    ->disabled(true)
                    ->numeric()
                    ->default(0),
                TextInput::make('undertime_hours')
                    ->required()
                    ->visible(false)
                    ->disabled(true)
                    ->numeric()
                    ->default(0.0),
                TextInput::make('daily_rate')
                    ->required()
                      ->visible(false)
                    ->disabled(true)
                    ->numeric()
                    ->default(0.0),
                TextInput::make('basic_salary')
                    ->required()
                      ->visible(false)
                    ->disabled(true)
                    ->numeric()
                    ->default(0.0),
                TextInput::make('overtime_salary')
                    ->required()
                      ->visible(false)
                    ->disabled(true)
                    ->numeric()
                    ->default(0.0),
                TextInput::make('holiday_pay')
                    ->required()
                      ->visible(false)
                    ->disabled(true)
                    ->numeric()
                    ->default(0.0),
                TextInput::make('other_earnings')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('gross_pay')
                    ->required()
                      ->visible(false)
                    ->disabled(true)
                    ->numeric()
                    ->default(0.0),
                TextInput::make('cash_advance')
                    ->required()
                    
                    ->numeric()
                    ->default(0.0),
                TextInput::make('shortages')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('sss_er')
                    ->required()
                      ->visible(false)
                    ->disabled(true)
                    ->numeric()
                    ->default(0.0),
                TextInput::make('sss_ee')
                    ->required()
                      ->visible(false)
                    ->numeric()
                    ->disabled(true)
                    ->default(0.0),
                TextInput::make('sss_loan')
                    ->required()
                    ->disabled(true)
                      ->visible(false)
                    ->numeric()
                    ->default(0.0),
                TextInput::make('sss_total')
                    ->required()
                      ->visible(false)
                    ->numeric()
                    ->disabled(true)
                    ->default(0.0),
                TextInput::make('philhealth_er')
                    ->required()
                    ->disabled(true)
                    ->numeric()
                      ->visible(false)
                    ->default(0.0),
                TextInput::make('philhealth_ee')
                    ->required()
                    ->disabled(true)
                    ->numeric()
                      ->visible(false)
                    ->default(0.0),
                TextInput::make('pagibig_er')
                    ->required()
                    ->disabled(true)
                      ->visible(false)
                    ->numeric()
                    ->default(0.0),
                TextInput::make('pagibig_ee')
                    ->required()
                    ->disabled(true)
                    ->numeric()
                      ->visible(false)
                    ->default(0.0),
                TextInput::make('pagibig_loan')
                    ->required()
                    ->disabled(true)
                    ->numeric()
                      ->visible(false)
                    ->default(0.0),
                TextInput::make('pagibig_total')
                    ->required()
                    ->disabled(true)
                      ->visible(false)
                    ->numeric()
                    ->default(0.0),
                TextInput::make('total_deductions')
                    ->required()
                      ->visible(false)
                    ->numeric()
                    ->disabled(true)
                    ->default(0.0),
                TextInput::make('net_pay')
                    ->required()
                    ->numeric()
                      ->visible(false)
                    ->disabled(true)
                    ->default(0.0),
                TextInput::make('status')
                    ->required()
                      ->visible(false)
                    ->disabled(true)
                    ->default('draft'),
            ])->columns(1);
    }
}
